# Generated by Django 5.2 on 2025-04-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReaccion',
            fields=[
                ('id_tipo_reaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VersionJuego',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_version', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='biblioteca.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='biblioteca.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='biblioteca.categoria')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='biblioteca.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='biblioteca.usuario')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='biblioteca.versionjuego')),
            ],
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id_reaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='biblioteca.publicacion')),
                ('tipo_reaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='biblioteca.tiporeaccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='biblioteca.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'publicacion', 'tipo_reaccion')},
            },
        ),
    ]
